config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
 # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: 'users#index'
   
   resources :users, only: %i[index]
  resources :groups, only: %i[index new create] do
    resources :operations, only: %i[index show new create]
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can :read, User
    can :read, Group
    can :read, Operation

    return unless user.present?

    can :manage, Group do |group|
      group.user == user
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/groug.rb
class Groug < ApplicationRecord
    belongs_to :user
    has_and_belongs_to_many :operations

    validates :name, presence: true, length: { maximum: 250 }
    validates :icon, presence: true, length: { maximum: 250 }

    def total_amount
        operations.sum(:amount)
    end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :operations

  validates :name, presence: true, length: { maximum: 250 }
  validates :icon, presence: true

  def total_amount
    operations.sum(:amount)
  end
end

app/models/groups_operation.rb
class GroupsOperation < ApplicationRecord
  belongs_to :group
  belongs_to :operation
end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
  has_and_belongs_to_many :groups

  validates :name, presence: true, length: { maximum: 250 }
  validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :groups
  has_many :operations

  validates :name, presence: true
  validates :role, inclusion: { in: %w[admin user], message: '%<value>s is not a valid role [admin, user]' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_sign_up_params, if: :devise_controller?

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name role email password])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name email password current_password role])
  end

  def after_sign_in_path_for(_resource_or_scope)
    groups_path
  end

  def after_sign_out_path_for(_resource_or_scope)
    root_path
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    authorize! :index, Group
    @groups = Group.order('created_at DESC')
  end

  def show
    @group = Group.includes(:operations).find(params[:id])
    @operations = @group.operations
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.new(group_params)

    if @group.save
      redirect_to groups_path, notice: 'Category was successfully created.'
    else
      render 'new', status: 422
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  def index
    @groups = Group.all.order(created_at: :desc)
    @transactions_by_group = {}

    # Group transactions by their associated group
    @groups.each do |group|
      @transactions_by_group[group] = group.operations.order(created_at: :desc)
    end

    @total_by_group = {}

    # Calculate total amount for each group
    @transactions_by_group.each do |group, transactions|
      @total_by_group[group] = transactions.sum(:amount)
    end
  end

  def show
    @group = Group.find(params[:group_id])
    @operations = @group.operations
    @operation = @operations.find(params[:id])
  end

  def new
    @group = Group.find(params[:group_id])
    @operation = @group.operations.new
  end

  def create
    @group = Group.find(params[:group_id])

    @operation = @group.operations.create(name: operation_params[:name], amount: operation_params[:amount],
                                          user_id: current_user.id, group_id: @group.id)

    if @operation.save
      # Handle the selected group IDs
      @operation.group_ids = params[:operation][:group_ids]

      redirect_to group_operations_path(@group), notice: 'Operation successfully created'
    else
      render :new
    end
  end

  private

  def operation_params
    params.require(:operation).permit(:name, :amount, :group_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/index.html.erb
<nav>
    <div class='burger_menu'>
      <%= link_to groups_path, class: 'back_btn' do %>
        <img src="https://img.icons8.com/material-outlined/24/ffffff/back--v1.png" alt="back"/>
      <% end %>
    </div>
    <p>CATEGORIES</p>
        <%= button_to "SIGN OUT", destroy_user_session_path, method: :delete, class: 'signout' %>
  </nav>

<div class="category-wrapper">
  <% @groups.each do |group| %>
    <%= link_to group_operations_path(group), class: 'group-item' do %>

    <div class="category-update">
      <p class="group-icon">
        <% if group.icon =~ /\.(png|jpg|jpeg|gif)$/ %>
          <%= image_tag group.icon, class: "group-icon2" %>
        <% else %>
          <%= group.icon %>
        <% end %>
      </p>
      <p class="group-name"><%= group.name %></p>
      <p class="group-amount">$<%= group.total_amount %></p>
      </div>
    <% end %>
  <% end %>
</div>


<footer id = 'new_category'>
<%=link_to 'ADD NEW CATEGORY', new_group_path, class: 'new_category_btn' %>
</footer>

app/views/groups/new.html.erb
<div class="new-container">
<nav>
    <div class='burger_menu'>
      <%= link_to groups_path, class: 'back_btn' do %>
        <img src="https://img.icons8.com/material-outlined/24/ffffff/back--v1.png" alt="back"/>
      <% end %>
    </div>
    <p>CATEGORY</p>
        <%= button_to "SIGN OUT", destroy_user_session_path, method: :delete, class: 'signout' %>
  </nav>
  
  <%= form_with(model: @group, url: groups_path, local: true, data: { turbo: false }) do |f| %>
  <%= f.text_field :name, placeholder: "Category Name", class: "new-group" %><br />
  <%= f.text_area :icon, placeholder: "Category Icon", class: "new-group" %><br />
  <div class="actions">
  <%= f.submit 'SAVE CATEGORY', class: "actions-btn" %>
  </div>
<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700&display=swap">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/operations/index.html.erb
<nav>
    <div class='burger_menu'>
      <%= link_to groups_path, class: 'back_btn' do %>
        <img src="https://img.icons8.com/material-outlined/24/ffffff/back--v1.png" alt="back"/>
      <% end %>
    </div>
    <p>TRANSACTIONS</p>
        <%= button_to "SIGN OUT", destroy_user_session_path, method: :delete, class: 'signout' %>
  </nav>

<div class="transaction-container">
  <div class="transaction-header">

    <div class="transaction-wrapper">
  <% @transactions_by_group.each do |group, transactions| %>
    <div class="group-container">
      <div class="group-info">
        <h3><%= group.name %></h3>
        <p class="total-haut">$<%= @total_by_group[group] %></p>
      </div>
      
      <div class="transactions-list">
        <% if transactions.present? %>
          <% transactions.each do |transaction| %>
            <div class="transaction-item">
              <h5 class="transaction-title"><%= transaction.name %></h5>
              <p class="transaction-amount">$<%= transaction.amount %></p>
            </div>
          <% end %>
        <% else %>
          <p>No transactions found for the <%= group.name %> Group.</p>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<footer id = 'new_category'>
<%=link_to 'ADD NEW TRANSACTION', new_group_operation_path, class: 'new_category_btn' %>
</footer>

app/views/operations/new.html.erb
<nav>
    <div class='burger_menu'>
      <%= link_to groups_path, class: 'back_btn' do %>
        <img src="https://img.icons8.com/material-outlined/24/ffffff/back--v1.png" alt="back"/>
      <% end %>
    </div>
    <p>TRANSACTION</p>
        <%= button_to "SIGN OUT", destroy_user_session_path, method: :delete, class: 'signout' %>
  </nav>

<%= form_for :operation, url: group_operations_path(@group) do |f| %>
  <div class="field">
    <%= f.text_field :name, placeholder: "Transaction Name", class: "transaction-field" %><br />
  </div>

  <div class="field">
    <%= f.text_area :amount, placeholder: "Transaction Amount", class: "transaction-field" %><br />
  </div>

  <div class="field">
    <%= f.label :group_ids, "Select Category", class: "group-choise" %><br />
    <%= f.collection_check_boxes :group_ids, Group.all, :id, :name, class: "form-check-input" %>
  </div>

  <div class="actions">
    <%= f.submit "SAVE TRANSACTION", class: "actions-btn"%>
  </div>
<% end %>

app/views/users/index.erb
<div class="splash-container">
<div class="splash-wrapper">
<h1 class="title">BUDGET APP</h1>

<%= link_to "LOG IN", new_user_session_path, class: "login" %>
<%= link_to "SIGN UP", new_user_registration_path, class: "signup" %>
</div>
</div>

<% if user_signed_in? %>
  <%= link_to 'Sign out', destroy_user_session_path, data: { turbo_method: :delete } %>
<% else %>
  <%= link_to 'Sign in', new_user_session_path %>
<% end %> 